#!/bin/bash
#
# (C) Crown Copyright 2023, the Met Office. All rights reserved.
#
#
set -euo pipefail

finally() {
    trap '' ERR
    trap '' EXIT
    if [[ -d "${WORKD:-}" ]]; then
        cd /
        rm -fr "${WORKD}"
    fi
}

HERE="$(cd "$(dirname "$0")" && pwd)"
THIS="$(basename "$0")"
NPROC=${NPROC:-$(nproc)}
WORKD="$(mktemp -d "${THIS}-XXXXXX" -t)"

trap finally ERR
trap finally EXIT

cd "${WORKD}"

GENERATOR=Unix\ Makefiles
if command -v ninja; then GENERATOR=Ninja; fi

# -- Configure
(   set -x;
    cmake -B . -S "${HERE}" -G "$GENERATOR" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DMPI_ARGS="--oversubscribe"


# -- Build
    cmake --build . -j "${NPROC}"


# -- Test
    env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
    ctest -j "$NPROC" --test-dir './opsinputs' --output-on-failure
)

exit
