#!/bin/bash
set -euo pipefail

finally() {
    trap '' ERR
    trap '' EXIT
    if [[ -d "${WORKD:-}" ]]; then
        cd /
        rm -fr "${WORKD}"
    fi
}

HERE="$(cd "$(dirname "$0")" && pwd)"
THIS="$(basename "$0")"
NPROC=${NPROC:-2}
WORKD="$(mktemp -d "${THIS}-XXXXXX" -t)"

trap finally ERR
trap finally EXIT

cd "${WORKD}"

# set -x
# sed 's:LD_LIBRARY_PATH=:LD_LIBRARY_PATH=/opt/view/lib\::g' /etc/profile.d/z10_spack_environment.sh > "${WORKD}/set_spack_env.sh"
# source ${WORKD}/set_spack_env.sh
# echo "$LD_LIBRARY_PATH"
# set +x

cp -a "${HERE}/shumlib" .
arch='vm-x86-gfortran-gcc'
(cd './shumlib' && make -f "./make/${arch}.mk")
prefix="${PREFIX:-/usr/local/}"
cp -p "./shumlib/build/${arch}/include/"* "${prefix}include/"
cp -p "./shumlib/build/${arch}/lib/"* "${prefix}lib/"
rm -fr './shumlib'

set -x
source /etc/profile.d/z10_spack_environment.sh
export SHUM_ROOT=$prefix
set +x

rm -f "${HERE}/opsinputs"
ln -s '..' "${HERE}/opsinputs"
ecbuild -S "${HERE}" -DMPI_ARGS="--oversubscribe"
make -j "${NPROC}"
env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
    ctest -j "${NPROC}" --output-on-failure --test-dir './opsinputs'

exit
