#!/bin/bash
set -euo pipefail

finally() {
    trap '' ERR
    trap '' EXIT
    if [[ -d "${WORKD:-}" ]]; then
        cd /
        rm -fr "${WORKD}"
    fi
}

HERE="$(cd "$(dirname "$0")" && pwd)"
THIS="$(basename "$0")"
NPROC=${NPROC:-2}
WORKD="$(mktemp -d "${THIS}-XXXXXX" -t)"

trap finally ERR
trap finally EXIT

cd "${WORKD}"

cp -a "${HERE}/shumlib" .
arch='vm-x86-gfortran-gcc'
(cd './shumlib' && make -f "./make/${arch}.mk")
prefix="${PREFIX:-/usr/local/}"
cp -p "./shumlib/build/${arch}/include/"* "${prefix}include/"
cp -p "./shumlib/build/${arch}/lib/"* "${prefix}lib/"
rm -fr './shumlib'

# - jcsda container requires manual sourcing of spack environment
source /etc/profile.d/z10_spack_environment.sh

# - override container shumlib (does not work)
export SHUM_ROOT=$prefix

rm -f "${HERE}/opsinputs"
ln -s '..' "${HERE}/opsinputs"
ecbuild -S "${HERE}" -DMPI_ARGS="--oversubscribe"
make -j "${NPROC}"
env OMPI_ALLOW_RUN_AS_ROOT=1 OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
    ctest -j "${NPROC}" --output-on-failure --test-dir './opsinputs'

exit
