---
name: UKMO_CI_Azure

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: build and test
    runs-on: jedi-self-hosted-rg
    env:
      PR: ${{ github.event.number }}
      REPO: ${{ github.event.repository.name }}
      BUNDLE: ${{ github.event.number }}-bundle

    steps:
      - name: checkout current
        uses: actions/checkout@v4
        with:
          path: ${{ env.PR }}
      - name: initiate bundle
        run: |
          mkdir -p ${{ env.BUNDLE }}/${{ env.REPO }}
          cp -r ${{ env.PR }}/ci/* ${{ env.BUNDLE }}/
          cp -r ${{ env.PR }}/* ${{ env.BUNDLE }}/${{ env.REPO }}

      - name: checkout jedicmake
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/jedicmake
          repository: JCSDA-internal/jedi-cmake
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: checkout oops
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/oops
          repository: JCSDA-internal/oops
          token: ${{ secrets.GH_PAT }}
      - name: matching branch checkout attempt oops ${{ github.head_ref }}
        if: github.event_name == 'pull_request'
        run: ./${{ env.BUNDLE }}/get-ref-branch ./${{ env.BUNDLE }}/oops

      - name: checkout ioda
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/ioda
          repository: JCSDA-internal/ioda
          token: ${{ secrets.GH_PAT }}
      - name: matching branch checkout attempt ioda ${{ github.head_ref }}
        if: github.event_name == 'pull_request'
        run: ./${{ env.BUNDLE }}/get-ref-branch ./${{ env.BUNDLE }}/ioda

      - name: checkout ufo
        uses: actions/checkout@v4
        with:
          path: ./${{ env.BUNDLE }}/ufo
          repository: JCSDA-internal/ufo
          token: ${{ secrets.GH_PAT }}
      - name: matching branch checkout attempt ufo ${{ github.head_ref }}
        if: github.event_name == 'pull_request'
        run: ./${{ env.BUNDLE }}/get-ref-branch ./${{ env.BUNDLE }}/ufo

      - name: build and test
        run: |
          az acr login --name ngmssboxjediacr
          docker run --rm \
            --entrypoint=/usr/local/src/${REPO}/${BUNDLE}/build-and-test \
            --workdir=/usr/local/src/${REPO}/${BUNDLE} \
            --volume $PWD/${BUNDLE}:/usr/local/src/${REPO}/${BUNDLE} \
            'ngmssboxjediacr.azurecr.io/jedibase:alma9'
