---
name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

env:
  REPO: ${{ github.event.repository.name }}
  PR: pr-${{ github.event.number }}

jobs:
  build1:
    if: |
      ( github.repository_owner == 'MetOffice' && github.event.pull_request.draft == false )
    name: gnu-openmpi (JCSDA)
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout current
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/${{ env.REPO }}
      - name: Initiate bundle
        run: cp ./${{ env.PR }}/${{ env.REPO }}/ci/* ./${{ env.PR }}/

      - name: Checkout jedicmake
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/jedicmake
          repository: JCSDA-internal/jedi-cmake
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Checkout oops
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/oops
          repository: JCSDA-internal/oops
          token: ${{ secrets.GH_PAT }}
      - name: Check build-group for oops
        if: github.event_name == 'pull_request'
        run: ./${{ env.PR }}/check-build-group.sh ./${{ env.PR }}/oops

      - name: Checkout ioda
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/ioda
          repository: JCSDA-internal/ioda
          token: ${{ secrets.GH_PAT }}
      - name: Check build-group for ioda
        if: github.event_name == 'pull_request'
        run: ./${{ env.PR }}/check-build-group.sh ./${{ env.PR }}/ioda

      - name: Checkout ufo
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/ufo
          repository: JCSDA-internal/ufo
          token: ${{ secrets.GH_PAT }}
      - name: Check build-group for ufo
        if: github.event_name == 'pull_request'
        run: ./${{ env.PR }}/check-build-group.sh ./${{ env.PR }}/ufo

      - name: build and test
        run: |
          docker run --rm \
            --entrypoint=/usr/local/src/${REPO}/${PR}/build-and-test \
            --workdir=/usr/local/src/${REPO}/${PR} \
            --volume ${PWD}/${PR}:/usr/local/src/${REPO}/${PR} \
            'jcsda/docker-gnu-openmpi-dev:latest'

  build2:
    if:
      ( github.repository_owner == 'MetOffice' && github.event.pull_request.draft == false )
    name: clang-mpich (JCSDA)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/${{ env.REPO }}
      - name: Initiate bundle
        run: cp ./${{ env.PR }}/${{ env.REPO }}/ci/* ./${{ env.PR }}/

      - name: Checkout jedicmake
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/jedicmake
          repository: JCSDA-internal/jedi-cmake
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Checkout oops
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/oops
          repository: JCSDA-internal/oops
          token: ${{ secrets.GH_PAT }}
      - name: Check build-group for oops
        if: github.event_name == 'pull_request'
        run: ./${{ env.PR }}/check-build-group.sh ./${{ env.PR }}/oops

      - name: Checkout ioda
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/ioda
          repository: JCSDA-internal/ioda
          token: ${{ secrets.GH_PAT }}
      - name: Check build-group for ioda
        if: github.event_name == 'pull_request'
        run: ./${{ env.PR }}/check-build-group.sh ./${{ env.PR }}/ioda

      - name: Checkout ufo
        uses: actions/checkout@v4
        with:
          path: ./${{ env.PR }}/ufo
          repository: JCSDA-internal/ufo
          token: ${{ secrets.GH_PAT }}
      - name: Check build-group for ufo
        if: github.event_name == 'pull_request'
        run: ./${{ env.PR }}/check-build-group.sh ./${{ env.PR }}/ufo

      - name: Build and Test
        run: |
          docker run --rm \
            --entrypoint=/usr/local/src/${REPO}/${PR}/build-and-test \
            --workdir=/usr/local/src/${REPO}/${PR} \
            --volume ${PWD}/${PR}:/usr/local/src/${REPO}/${PR} \
            'jcsda/docker-clang-mpich-dev:latest'
