name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI_IMAGE: ghcr.io/metoffice/opsinputs-ci:latest
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repo
        uses: actions/checkout@v2
      - name: login to ghcr
        run: |
          docker login ghcr.io -u ${{ github.actor }} \
            --password-stdin < <(printenv GITHUB_TOKEN)
      - name: pull CI image
        run: |
          docker pull "${CI_IMAGE}"
      - name: build and test
        run: |
          docker run --rm --workdir=/opt/opsinputs --volume $PWD:/opt/opsinputs \
            "${CI_IMAGE}"
