---
name: CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  lint:
    name: Lint CMakeLists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install cmakelint
        run: |
          python3 -m pip install cmakelint
      - name: Lint
        run: |
          find -type f '(' -name 'CMakeLists.txt' -o -name '*.cmake' ')' \
            -exec cmakelint '{}' ';'
  build:
    if: |
      ( github.repository_owner == 'MetOffice' && github.event.pull_request.draft == false )
    name: gnu-openmpi (UKMO)
    runs-on: jedi-self-hosted-rg
    environment: CI
    env:
      REPO: ${{ github.event.repository.name }}
      PR: pr-${{ github.event.number }}

    steps:
      - name: Pre-submit cleanup
        run: |
          rm -fr ./${{ env.PR }} || true
          ls -al ./
      - name: Checkout current
        uses: actions/checkout@v5
        with:
          path: ./${{ env.PR }}/${{ env.REPO }}
      - name: Initiate bundle
        run: cp -a ./${{ env.PR }}/${{ env.REPO }}/ci/* ./${{ env.PR }}/

      - name: Checkout jedicmake
        uses: actions/checkout@v5
        with:
          path: ./${{ env.PR }}/jedicmake
          repository: JCSDA-internal/jedi-cmake
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Checkout oops
        uses: actions/checkout@v5
        with:
          path: ./${{ env.PR }}/oops
          repository: JCSDA-internal/oops
          token: ${{ secrets.GH_PAT }}
      - name: Check build-group for oops
        if: github.event_name == 'pull_request'
        run: ./${{ env.PR }}/check-build-group.sh ./${{ env.PR }}/oops

      - name: Checkout ioda
        uses: actions/checkout@v5
        with:
          path: ./${{ env.PR }}/ioda
          repository: JCSDA-internal/ioda
          token: ${{ secrets.GH_PAT }}
      - name: Check build-group for ioda
        if: github.event_name == 'pull_request'
        run: ./${{ env.PR }}/check-build-group.sh ./${{ env.PR }}/ioda

      - name: Checkout ufo
        uses: actions/checkout@v5
        with:
          path: ./${{ env.PR }}/ufo
          repository: JCSDA-internal/ufo
          token: ${{ secrets.GH_PAT }}
      - name: Check build-group for ufo
        if: github.event_name == 'pull_request'
        run: ./${{ env.PR }}/check-build-group.sh ./${{ env.PR }}/ufo

      - name: Build and Test
        env:
          # Container environment
          WORKDIR: /var/tmp/${{ env.REPO}}/${{ env.PR }}

        run: |
          az acr login --name ngmssboxjediacr
          docker run --rm \
            --name ${REPO}_${PR}_${GITHUB_SHA::7} \
            --volume ${{ github.workspace }}/${PR}:${WORKDIR} \
            --workdir=${WORKDIR} \
            --entrypoint=${WORKDIR}/build-and-test \
            'ngmssboxjediacr.azurecr.io/jedibase:alma9'

      - name: Cleanup workspace
        working-directory: ${{github.workspace}}
        run: rm -fr ${{ env.PR }} || true
