---
name: Check Label

on:
  # push:
  #   branches: [feature/check_label]
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  ready-to-merge:
    # if: "!contains(github.event.pull_request.labels.*.name, 'ready to merge')"
    runs-on: ubuntu-latest

    steps:
      - name: Fail if PR is not labelled as ready to merge
        if: "!contains(github.event.pull_request.labels.*.name,'ready to merge')"
        run: |
          echo "This PR is not yet ready to merge."
          exit 1

      - name: Pass if PR is labelled as ready to merge
        if: "contains(github.event.pull_request.labels.*.name,'ready to merge')"
        run: |
          echo "This PR is ready to merge."
