name: Check Label

on:
  pull_request:
  # branches:
  #   - main
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  ready-to-merge:
    if: contains(github.event.pull_request.labels.*.name, 'ready to merge')
    runs-on: ubuntu-latest
    steps:
      - name: Pass if PR is labelled as ready to merge
        run: |
          echo "This PR is ready to merge."
          exit 0
